{
    "Service": "/First_MDK/Services/com_sap_edm_sampleservice_v4.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "Products",
            "Query": "Products"
        },
        {
            "Name": "PurchaseOrderHeaders",
            "Query": "PurchaseOrderHeaders"
        },
        {
            "Name": "PurchaseOrderItems",
            "Query": "PurchaseOrderItems"
        }
    ],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/First_MDK/Actions/com_sap_edm_sampleservice_v4/Service/SyncFailureMessage.action",
    "OnSuccess": "/First_MDK/Rules/com_sap_edm_sampleservice_v4/ErrorArchive_CheckForSyncError.js"
}