{
	"_Type": "Action.Type.ODataService.DeleteEntity",
	"ActionResult": {
		"_Name": "Customers_DeleteEntity"
	},
	"OnFailure": "/First_MDK/Actions/DeleteCustomerEntityFailureMessage.action",
	"OnSuccess": "/First_MDK/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/First_MDK/Services/com_sap_edm_sampleservice_v4.service",
		"EntitySet": "Customers",
		"ReadLink": "{@odata.readLink}"
	}
}